stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

before_script:
  - sleep 5
  - echo -n $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build:
  stage: build
  tags:
    - chigisoft
    - shared
  only:
    - tags
  script:
    - echo $IMAGE_TAG
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
